-- =========================================================
-- OmegaFiguresWeb - Base SQL oficial para Supabase/PostgreSQL
-- Ejecutar en Supabase > SQL Editor
--
-- Versión corregida para evitar errores en JetBrains:
-- - No usa pg_roles
-- - No usa to_regrole()
-- - No referencia directamente order_items_id_seq
-- - Usa schema public de forma explícita
-- =========================================================

CREATE SCHEMA IF NOT EXISTS public;
SET search_path TO public;

-- =========================================================
-- Limpiar tablas anteriores
-- =========================================================

DROP TABLE IF EXISTS public.order_items CASCADE;
DROP TABLE IF EXISTS public.orders CASCADE;
DROP TABLE IF EXISTS public.products CASCADE;
DROP TABLE IF EXISTS public.users CASCADE;

-- =========================================================
-- Tabla users
-- =========================================================

CREATE TABLE public.users (
    id TEXT PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(160) NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    role VARCHAR(20) NOT NULL CHECK (role IN ('ADMIN', 'EMPLEADO', 'CLIENTE')),
    phone VARCHAR(40),
    address TEXT,
    city VARCHAR(80),
    country VARCHAR(80),
    birth_date DATE,
    interests TEXT[] DEFAULT '{}',
    newsletter BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =========================================================
-- Tabla products
-- =========================================================

CREATE TABLE public.products (
    id TEXT PRIMARY KEY,
    name VARCHAR(160) NOT NULL,
    category VARCHAR(80) NOT NULL,
    genre VARCHAR(80) NOT NULL,
    description TEXT NOT NULL,
    price NUMERIC(10,2) NOT NULL CHECK (price >= 0),
    stock INT NOT NULL CHECK (stock >= 0),
    image TEXT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    featured BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =========================================================
-- Tabla orders
-- =========================================================

CREATE TABLE public.orders (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    status VARCHAR(20) NOT NULL CHECK (status IN ('PENDIENTE', 'APROBADA', 'RECHAZADA', 'ENVIADA')),
    total NUMERIC(10,2) NOT NULL CHECK (total >= 0),
    customer_name VARCHAR(160),
    shipping_phone VARCHAR(40),
    shipping_address TEXT,
    shipping_city VARCHAR(100),
    shipping_country VARCHAR(100),
    shipping_notes TEXT,
    payment_method VARCHAR(30) DEFAULT 'CARD',
    payment_brand VARCHAR(40),
    payment_last4 VARCHAR(4)
);

-- =========================================================
-- Tabla order_items
-- =========================================================

CREATE TABLE public.order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id TEXT NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
    product_id TEXT REFERENCES public.products(id) ON DELETE SET NULL,
    name VARCHAR(160) NOT NULL,
    price NUMERIC(10,2) NOT NULL CHECK (price >= 0),
    quantity INT NOT NULL CHECK (quantity > 0),
    image TEXT NOT NULL
);

-- =========================================================
-- Índices
-- =========================================================

CREATE INDEX idx_users_email ON public.users(email);
CREATE INDEX idx_users_role ON public.users(role);
CREATE INDEX idx_products_genre ON public.products(genre);
CREATE INDEX idx_products_category ON public.products(category);
CREATE INDEX idx_orders_user_id ON public.orders(user_id);
CREATE INDEX idx_orders_status ON public.orders(status);
CREATE INDEX idx_order_items_order_id ON public.order_items(order_id);

-- =========================================================
-- Row Level Security
-- NOTA IMPORTANTE:
-- Estas políticas están abiertas para proyecto académico/prototipo
-- con GitHub Pages + Supabase anon key.
-- Para producción real se debe usar Supabase Auth y políticas por usuario.
-- =========================================================

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY omega_users_select ON public.users
FOR SELECT USING (true);

CREATE POLICY omega_users_insert ON public.users
FOR INSERT WITH CHECK (true);

CREATE POLICY omega_users_update ON public.users
FOR UPDATE USING (true)
WITH CHECK (true);

CREATE POLICY omega_products_select ON public.products
FOR SELECT USING (true);

CREATE POLICY omega_products_insert ON public.products
FOR INSERT WITH CHECK (true);

CREATE POLICY omega_products_update ON public.products
FOR UPDATE USING (true)
WITH CHECK (true);

CREATE POLICY omega_orders_select ON public.orders
FOR SELECT USING (true);

CREATE POLICY omega_orders_insert ON public.orders
FOR INSERT WITH CHECK (true);

CREATE POLICY omega_orders_update ON public.orders
FOR UPDATE USING (true)
WITH CHECK (true);

CREATE POLICY omega_order_items_select ON public.order_items
FOR SELECT USING (true);

CREATE POLICY omega_order_items_insert ON public.order_items
FOR INSERT WITH CHECK (true);

CREATE POLICY omega_order_items_update ON public.order_items
FOR UPDATE USING (true)
WITH CHECK (true);

-- =========================================================
-- Permisos para Supabase
-- En Supabase el rol anon existe.
-- Si ejecutas esto en PostgreSQL local y no existe anon,
-- puedes comentar estas líneas GRANT.
-- =========================================================

GRANT USAGE ON SCHEMA public TO anon;

GRANT SELECT, INSERT, UPDATE ON TABLE public.users TO anon;
GRANT SELECT, INSERT, UPDATE ON TABLE public.products TO anon;
GRANT SELECT, INSERT, UPDATE ON TABLE public.orders TO anon;
GRANT SELECT, INSERT, UPDATE ON TABLE public.order_items TO anon;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon;

-- =========================================================
-- Usuarios iniciales
-- Contraseñas:
-- admin@omegafigures.com     / admin123
-- empleado@omegafigures.com  / empleado123
-- cliente@omegafigures.com   / cliente123
-- Los password_hash son SHA-256 del texto plano.
-- =========================================================

INSERT INTO public.users (
    id, name, email, password_hash, role, phone, address, city, country,
    birth_date, interests, newsletter, created_at
) VALUES
(
    'u_admin',
    'Administrador Omega',
    'admin@omegafigures.com',
    '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9',
    'ADMIN',
    '+593000000000',
    'Oficina principal',
    'Quito',
    'Ecuador',
    NULL,
    ARRAY['Estadísticas'],
    FALSE,
    '2026-05-01 09:00:00+00'
),
(
    'u_emp',
    'Empleado Omega',
    'empleado@omegafigures.com',
    'ccc13e8ab0819e3ab61719de4071ecae6c1d3cd35dc48b91cad3481f20922f9f',
    'EMPLEADO',
    '+593000000001',
    'Sucursal online',
    'Quito',
    'Ecuador',
    NULL,
    ARRAY['Gestión'],
    FALSE,
    '2026-05-02 09:00:00+00'
),
(
    'u_cli',
    'Cliente Omega',
    'cliente@omegafigures.com',
    '09a31a7001e261ab1e056182a71d3cf57f582ca9a29cff5eb83be0f0549730a9',
    'CLIENTE',
    '+593000000002',
    'Dirección principal',
    'Quito',
    'Ecuador',
    NULL,
    ARRAY['Anime','Promociones'],
    TRUE,
    '2026-05-03 09:00:00+00'
);

-- =========================================================
-- Productos iniciales
-- =========================================================

INSERT INTO public.products (
    id, name, category, genre, description, price, stock, image,
    active, featured, created_at
) VALUES
(
    'p1',
    'Cyberpunk Collector Bot',
    'Figura',
    'Cyberpunk',
    'Figura futurista con casco neón, acabado tecnológico y base decorativa.',
    54.99,
    9,
    'assets/img/figure-1.svg',
    TRUE,
    TRUE,
    NOW()
),
(
    'p2',
    'Omega Ninja Shadow',
    'Figura',
    'Anime',
    'Figura ninja de colección con traje oscuro, armas decorativas y estilo moderno.',
    39.99,
    12,
    'assets/img/figure-2.svg',
    TRUE,
    TRUE,
    NOW()
),
(
    'p3',
    'Retro Pixel Warrior',
    'Coleccionable',
    'Retro',
    'Figura inspirada en videojuegos clásicos, perfecta para amantes del estilo vintage.',
    24.99,
    18,
    'assets/img/figure-3.svg',
    TRUE,
    TRUE,
    NOW()
),
(
    'p4',
    'Dragon Guardian Statue',
    'Estatua',
    'Fantasía',
    'Estatua de dragón con acabado de fantasía, textura detallada y base de exhibición.',
    74.99,
    7,
    'assets/img/figure-4.svg',
    TRUE,
    TRUE,
    NOW()
),
(
    'p5',
    'Galaxy Space Ranger',
    'Figura',
    'Ciencia ficción',
    'Figura espacial con armadura brillante y detalles galácticos.',
    64.50,
    11,
    'assets/img/figure-5.svg',
    TRUE,
    FALSE,
    NOW()
),
(
    'p6',
    'Samurai Flame Edition',
    'Coleccionable',
    'Anime',
    'Samurái edición especial con colores intensos y accesorios intercambiables.',
    49.90,
    14,
    'assets/img/figure-6.svg',
    TRUE,
    FALSE,
    NOW()
),
(
    'p7',
    'Dark Knight Mini Statue',
    'Estatua',
    'Héroes',
    'Mini estatua de estilo oscuro para exhibición en escritorio o repisa.',
    34.75,
    16,
    'assets/img/figure-7.svg',
    TRUE,
    FALSE,
    NOW()
),
(
    'p8',
    'Arcade Robot Classic',
    'Figura',
    'Retro',
    'Robot de colección con estética arcade y acabado brillante.',
    29.99,
    20,
    'assets/img/figure-8.svg',
    TRUE,
    FALSE,
    NOW()
);

-- =========================================================
-- Compras iniciales
-- =========================================================

INSERT INTO public.orders (
    id, user_id, created_at, status, total,
    customer_name, shipping_phone, shipping_address, shipping_city, shipping_country,
    shipping_notes, payment_method, payment_brand, payment_last4
) VALUES
('o1', 'u_cli', '2026-05-04 11:20:00+00', 'PENDIENTE', 54.99, 'Cliente Omega', '+593000000002', 'Dirección principal', 'Quito', 'Ecuador', 'Pedido inicial de prueba', 'CARD', 'VISA', '4242'),
('o2', 'u_cli', '2026-05-05 15:45:00+00', 'APROBADA', 49.98, 'Cliente Omega', '+593000000002', 'Dirección principal', 'Quito', 'Ecuador', 'Compra aprobada inicial', 'TRANSFER', 'TRANSFERENCIA', NULL);

INSERT INTO public.order_items (
    order_id, product_id, name, price, quantity, image
) VALUES
('o1', 'p1', 'Cyberpunk Collector Bot', 54.99, 1, 'assets/img/figure-1.svg'),
('o2', 'p3', 'Retro Pixel Warrior', 24.99, 2, 'assets/img/figure-3.svg');

-- =========================================================
-- Verificación final
-- =========================================================

SELECT 'users' AS tabla, COUNT(*) AS total FROM public.users
UNION ALL
SELECT 'products' AS tabla, COUNT(*) AS total FROM public.products
UNION ALL
SELECT 'orders' AS tabla, COUNT(*) AS total FROM public.orders
UNION ALL
SELECT 'order_items' AS tabla, COUNT(*) AS total FROM public.order_items;
